version: '3.7'

services:
    fedachat:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: fedachat
        ports:
            - '9000:9000'
        volumes:
            - ../:/app
